### ISSUE TITLE
Sync spec to logger repos

### ISSUE THREAD

**Issue by felixbarny** [elastic/ecs-logging#30]
Similar to https://github.com/elastic/apm/pull/231, let's also sync the [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json) to the individual ECS loggers.

As an MVP, we can start with the Java logger and then add others gradually.

```yaml
loggers:
  - REPO: "ecs-logging-java"
    SPEC_PATH: "ecs-logging-core/src/test/resources/spec"
```
